# Generated by Django 6.0.2 on 2026-02-24 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistive_tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('canal_id', models.CharField(blank=True, max_length=100)),
                ('canal_nome', models.CharField(blank=True, max_length=200)),
                ('idioma', models.CharField(blank=True, max_length=10)),
                ('duracao_sec', models.IntegerField(blank=True, null=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('relevancia', models.FloatField(default=0.0)),
                ('fonte', models.CharField(blank=True, max_length=255)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='assistive_tech.tecnologiaassistiva')),
            ],
        ),
    ]
