# Generated by Django 6.0.2 on 2026-02-15 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistive_tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avaliacao', 'Avaliação'), ('usou', 'Usou'), ('nao_usou', 'Não usou'), ('recomendacao_aceita', 'Recomendação aceita'), ('rejeitada', 'Rejeitada')], default='avaliacao', max_length=30)),
                ('avaliacao', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('eficaz', models.BooleanField(null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='assistive_tech.tecnologiaassistiva')),
            ],
        ),
    ]
