# Generated by Django 6.0.2 on 2026-02-24 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncapacidadeFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TecnologiaAssistiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('servico', 'Serviço')], max_length=20)),
                ('categoria_iso', models.CharField(blank=True, max_length=20, null=True)),
                ('subtipo', models.CharField(blank=True, max_length=80)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('versao', models.CharField(blank=True, max_length=50)),
                ('licenca', models.CharField(choices=[('gratuito', 'Gratuito'), ('freemium', 'Freemium'), ('pago', 'Pago'), ('open-source', 'Código aberto')], default='gratuito', max_length=20)),
                ('nivel_complexidade', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=10)),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('idiomas_supported', models.CharField(blank=True, max_length=200)),
                ('requisitos', models.TextField(blank=True)),
                ('possui_video', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('fonte', models.CharField(blank=True, max_length=255)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TA_Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataforma_tas', to='assistive_tech.plataforma')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_plataformas', to='assistive_tech.tecnologiaassistiva')),
            ],
            options={
                'verbose_name': 'TA x Plataforma',
                'verbose_name_plural': 'TAs x Plataformas',
                'constraints': [models.UniqueConstraint(fields=('tecnologia', 'plataforma'), name='ux_tecnologia_plataforma')],
            },
        ),
        migrations.CreateModel(
            name='TA_Incapacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incapacidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inc_tas', to='assistive_tech.incapacidadefuncional')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_incapacidades', to='assistive_tech.tecnologiaassistiva')),
            ],
            options={
                'verbose_name': 'TA x Incapacidade',
                'verbose_name_plural': 'TAs x Incapacidades',
                'constraints': [models.UniqueConstraint(fields=('tecnologia', 'incapacidade'), name='ux_tecnologia_incapacidade')],
            },
        ),
        migrations.CreateModel(
            name='TA_Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='def_tas', to='assistive_tech.deficiencia')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_deficiencias', to='assistive_tech.tecnologiaassistiva')),
            ],
            options={
                'verbose_name': 'TA x Deficiência',
                'verbose_name_plural': 'TAs x Deficiências',
                'constraints': [models.UniqueConstraint(fields=('tecnologia', 'deficiencia'), name='ux_tecnologia_deficiencia')],
            },
        ),
        migrations.CreateModel(
            name='TA_Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexto_tas', to='assistive_tech.contextouso')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_contextos', to='assistive_tech.tecnologiaassistiva')),
            ],
            options={
                'verbose_name': 'TA x Contexto',
                'verbose_name_plural': 'TAs x Contextos',
                'constraints': [models.UniqueConstraint(fields=('tecnologia', 'contexto'), name='ux_tecnologia_contexto')],
            },
        ),
    ]
