# Generated by Django 6.0.2 on 2026-02-15 22:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistive_tech', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('consentimento_dados', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro'), ('NaoInformado', 'Não informado')], default='NaoInformado', max_length=20)),
                ('nivel_tecnologico', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=10)),
                ('orcamento', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=10)),
                ('idioma_preferido', models.CharField(default='pt-BR', max_length=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_deficiencias', to='assistive_tech.deficiencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_deficiencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário x Deficiência',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'deficiencia'), name='ux_usuario_deficiencia')],
            },
        ),
        migrations.CreateModel(
            name='Usuario_Incapacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo')], default='moderado', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('incapacidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_incapacidades', to='assistive_tech.incapacidadefuncional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_incapacidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário x Incapacidade',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'incapacidade'), name='ux_usuario_incapacidade')],
            },
        ),
        migrations.CreateModel(
            name='Usuario_Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_plataformas', to='assistive_tech.plataforma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_plataformas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário x Plataforma',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'plataforma'), name='ux_usuario_plataforma')],
            },
        ),
        migrations.CreateModel(
            name='Usuario_Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=200)),
                ('preferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_preferencias', to='assistive_tech.preferencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário x Preferência',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'preferencia'), name='ux_usuario_preferencia')],
            },
        ),
    ]
