# Generated by Django 6.0.2 on 2026-02-15 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistive_tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_usuario', models.JSONField()),
                ('score', models.FloatField()),
                ('metodo', models.CharField(choices=[('content-based', 'Baseado em conteúdo'), ('hybrid', 'Híbrido'), ('collaborative', 'Colaborativo')], default='content-based', max_length=20)),
                ('contexto', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TAFeatureVector',
            fields=[
                ('tecnologia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assistive_tech.tecnologiaassistiva')),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
