# Generated by Django 6.0.2 on 2026-02-15 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistive_tech', '0001_initial'),
        ('recommendations', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFeatureVector',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='recomendacaolog',
            name='tecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_log', to='assistive_tech.tecnologiaassistiva'),
        ),
        migrations.AddField(
            model_name='recomendacaolog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
